services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zadatak-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - db
      - mailpit

  nginx:
    image: nginx:1.27-alpine
    container_name: zadatak-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: zadatak-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: zadatak-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mysql_data: